### ISSUE TITLE
ING-Diba error

### ISSUE THREAD

**Issue by gitviola** [playtestcloud/ruby_fints#1]
When using `ruby_fints` with ING-Diba it throws this error:

```sh
/usr/local/bundle/gems/ruby_fints-0.0.1/lib/fints/response.rb:28:in `get_summary_by_segment': segment HIRMG (FinTS::SegmentNotFoundError)
	from /usr/local/bundle/gems/ruby_fints-0.0.1/lib/fints/response.rb:38:in `successful?'
	from /usr/local/bundle/gems/ruby_fints-0.0.1/lib/fints/dialog.rb:82:in `send_msg'
	from /usr/local/bundle/gems/ruby_fints-0.0.1/lib/fints/dialog.rb:39:in `sync'
	from /usr/local/bundle/gems/ruby_fints-0.0.1/lib/fints/client.rb:19:in `get_sepa_accounts'
```

Do you have any idea why this happens? I tried it with the php lib and it worked fine.

**Comment by mkilling** [comment]
Thanks for reporting this. Unfortunately, this library has only been tested with a Sparkasse account and we are unable to debug this ourselves as we don‘t have a ING-DiBa account.

If you have the time and capacity to look into this yourself I‘d be happy to assist though. A good first step would be to test if https://github.com/raphaelm/python-fints works with your account. If python-fints works and this lib does not it would be relatively easy to find out where the discrepancy is.

**Comment by gitviola** [comment]
Hi @mkilling, thanks for your fast reply.

I just tried it with the python library and it works with my ING-DiBa accounts. It returns the list of my sepa accounts. It would be great if you could assist me because I'm not familiar with the FinTs specifications at all.

**Comment by mkilling** [comment]
Very interesting. Can you try what happens when you use this branch? https://github.com/playtestcloud/ruby_fints/tree/ing-diba

**Comment by gitviola** [comment]
@mkilling that works :)

**Comment by mkilling** [comment]
Cool. I suggest you use that branch for now and after the holidays we‘ll think about merging this into master. I‘ll leave this issue open until then.

**Comment by gitviola** [comment]
Yes, as you suggested I'll use that branch you created for now. Thank you very much!
Happy Holidays 🎄
